### ISSUE TITLE
LinVst related AUR packages are gone

### ISSUE THREAD

**Issue by Goli4thus** [usrmusicman/PKGBUILDS#1]
Hi usrmusicman,

@perlindgren some time ago informed about your AUR packages related to LinVst and LinVstManager are gone (see [here](https://github.com/Goli4thus/linvstmanager/issues/16)).

I already had created an issue on your previous PKGBUILD related repo, but I guess that one got lost.
Anyway, are you aware of them being gone from AUR?

PS: osxmidi did bring back the "-X" bridge versions after all it seems.

**Comment by usrmusicman** [comment]
No longer maintained in the AUR, my packages are at
https://github.com/usrmusicman/PKGBUILDS now as it is easier to maintain
them. Also LinVst-X and LinVst3-X are no longer even available by the
author osxmidi. If you need intercommunicating VST Plugins under wine then
try this project https://github.com/robbert-vdh/yabridge as a solution and
there is a package for it in the AUR called yabridge.

**Comment by Goli4thus** [comment]
Well, they at least seem to be available once again (see https://github.com/osxmidi).

Anyway, I have no experience so far with the AUR from a maintainer's point of view, so I can't judge how cumbersome it is.
But I guess one big drawback of only hosting the PKGBUILDs on github will be lots of people never even becoming aware that they exist.
I could add a link re LinvstManager in my README. Maybe some will still prefer to download and execute a PKGBUILD instead of following the install instructions.

**Comment by Goli4thus** [comment]
OK, I've added a link to your PKGBUILD in the README (a5217386b35462b3963afce9f5ffae257ee3ec14).
Let's see how this turns out.

**Comment by madskjeldgaard** [comment]
Why not put these back on aur? Quite a few people used/depended on/liked these and they now have to do detective work to refind the pkgbuilds.
